name: Build

on: push

env:
  BASE_IMAGE_FOR_LATEST: "buster-backports"
  IMAGE_NAME: "pitop/git-buildpackage"
  DEPLOY_BRANCH: "develop"

jobs:
  build-push-docker-hub:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        base_image: ["buster-backports", "bullseye"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/develop'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine if using "latest" tag
        run: |
          base_image_is_stable=false
          if [[ "${{ matrix.base_image }}" == "${{ env.BASE_IMAGE_FOR_LATEST }}" ]]; then
            base_image_is_stable=true
          fi

          echo "USE_LATEST_TAG=${base_image_is_stable}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ env.USE_LATEST_TAG }}
            prefix=${{ matrix.base_image }}-,onlatest=false
          tags: |
            type=ref,event=branch

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: DEBIAN_BASE_IMAGE=${{ matrix.base_image }}
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/develop' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show image digest
        if: github.ref == 'refs/heads/develop'
        run: echo ${{ steps.docker_build_push.outputs.digest }}
